version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: hotel_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PGUSER: admin_db
      PGPASSWORD: admin_password
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: hotel_db
